//------------------------------------------------------------//

### CRUD Admin
POST http://localhost:5000/admin
Content-Type: application/json

{
    "nama": "ecaa",
    "username": "ecapedeh",
    "password": "ecantik29",
    "role": "Admin"
}

### Login
POST http://localhost:5000/login
Content-Type: application/json

{
    "username": "ecapedeh",
    "password": "ecantik29"
}

###
# GET http://localhost:5000/admin

###
# POST http://localhost:5000/admin/register
# Content-Type: application/json

# {
#     "username": "helsa",
#     "password": "helsa4213"
# }

###
# POST http://localhost:5000/admin/login
# Content-Type: application/json

# {
#     "username": "helsa",
#     "password": "helsa4213"
# }

//------------------------------------------------------------//

### CRUD DATA DIRI (Personal)
POST http://localhost:5000/personal
Content-Type: application/json

{
    "foto": "url/",
    "nama": "Muhammad Daffa Raihandika",
    "tempat_lahir" : "Bandung",
    "tanggal_lahir" : "2003-05-13",
    "usia" : 20,
    "tinggi_badan" : 160.0,
    "berat_badan" : 45.0,
    "alamat" : "Kota Cimahi, Jawa Barat, Indonesia",
    "agama" : "Islam",
    "jenis_kelamin" : "Perempuan",
    "telp" : "081572548494",
    "email" : "helsa.alika.tif421@polban.ac.id",
    "status" : "Mahasiswa",
    "id_akun": 2
}

###
GET http://localhost:5000/personal

###
GET http://localhost:5000/personal/5

###
PATCH http://localhost:5000/personal/1
Content-Type: application/json

{
    "nama": "Helsa Alika"
}

###
DELETE http://localhost:5000/personal/10
//------------------------------------------------------------//

### CRUD Portofolio
POST http://localhost:5000/portofolio
Content-Type: application/json

{
    "id_person": 1,
    "nama_portofolio": "CRUD expressJs1",
    "file_portofolio": "url/portofolio/expressJs1.pdf"
}

### Menampilkan semua portofolio berdasarkan id_person
GET http://localhost:5000/portofolio/1

### Menampilkan satu portofolio yang dipilih
GET http://localhost:5000/portofolio/1/2

### edit portofolio
PATCH http://localhost:5000/portofolio/2
Content-Type: application/json

{
    "nama_portofolio": "Ubah portofolioooww"
}

###
DELETE http://localhost:5000/portofolio/1

//------------------------------------------------------------//

### CRUD Pendidikan
POST http://localhost:5000/pendidikan
Content-Type: application/json

{
    "id_person": 1,
    "instansi_pendidikan": "SMAN 2 Ngamprah",
    "jurusan": "IPS",
    "tahun_mulai_ajaran": "2017-09-01",
    "tahun_akhir_ajaran": "2020-06-30"
}

###
GET http://localhost:5000/pendidikan/1

###
GET http://localhost:5000/pendidikan/1/1

###
PATCH http://localhost:5000/pendidikan/1
Content-Type: application/json

{
    "id_person": 1,
    "instansi_pendidikan": "SMAN 2 Cijerah",
    "jurusan": "IPS",
    "tahun_mulai_ajaran": "2017-09-01",
    "tahun_akhir_ajaran": "2020-06-30"
}

###
DELETE http://localhost:5000/pendidikan/2

//------------------------------------------------------------//


# CRUD Organisasi

###Create an Organisasi 
POST http://localhost:5000/organisasi 
Content-Type: application/json

{
"id_person": 1, 
"nama_organisasi": "BEM Kema Polban", 
"posisi": "Ketua Departemen Kominfo", 
"tanggal_mulai_menjabat": "2022-01-25", 
"tanggal_akhir_menjabat": "2023-12-29"
}

### Get All Organisasi by id_person 
GET http://localhost:5000/organisasi/1

### Get a Specific Organisasi by id_person and id_organisasi 
GET http://localhost:5000/organisasi/1/1

### Update an Organisasi 
PATCH http://localhost:5000/organisasi/1 
Content-Type: application/json

{
"posisi": "Ketua Departemen Kominfo"
}

### Delete an Organisasi 
DELETE http://localhost:5000/organisasi/1

# CRUD Skill

### Create a Skill 
POST http://localhost:5000/skill 
Content-Type: application/json

{
    "id_person": 1, 
    "nama_skill": "Ruby", 
    "capability": "Expert dalam menggunakan bahasa Ruby"
}

### Get All Skill by id_person 
GET http://localhost:5000/skill/1

### Get a Specific Skill by id_person and id_skill 
GET http://localhost:5000/skill/1/1

### Update a Skill 
PATCH http://localhost:5000/skill/1 
Content-Type: application/json

{
"capability": "Expert dalam menggunakan bahasa Ruby dan Python"
}

###
DELETE http://localhost:5000/skill/1