### CRUD Admin
POST http://localhost:5000/admin
Content-Type: application/json

{
    "username": "helsa",
    "password": "helsa4213"
}

###
GET http://localhost:5000/admin


### CRUD DATA DIRI
POST http://localhost:5000/personal
Content-Type: application/json

{
    "photo": "url/",
    "name": "Helsa Alika Femiani",
    "date_of_birth" : "2003-05-13",
    "age" : 20,
    "address" : "Kota Cimahi, Jawa Barat, Indonesia",
    "religion" : "Islam",
    "gender" : "Female",
    "phone" : "081572548494",
    "email_index" : "helsa.alika.tif421@polban.ac.id",
    "status" : "Mahasiswa",
    "id_portofolio" : 1,
}

###
GET http://localhost:5000/personal

##### END OF CRUD DATA DIRI (PERSONAL) ######

### CRUD Portofolio
POST http://localhost:5000/add-porto
Content-Type: application/json

{
    "id_person": 2,
    "nama_portofolio": "CRUD Springboot",
    "file_portofolio": "url/portofolio/springboot.pdf"
}

### Menampilkan semua portofolio berdasarkan id_person
GET http://localhost:5000/show-portofolio/2

### Menampilkan satu portofolio yang dipilih
GET http://localhost:5000/show-portofolio/2/4

### edit portofolio
PATCH http://localhost:5000/edit-portofolio/4
Content-Type: application/json

{
    "nama_portofolio": "Ubah portofolioooww"
}

###
DELETE http://localhost:5000/delete-portofolio/4
